name: flutter_aura
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Dependencias de la App ---
  flutter_secure_storage: ^9.2.2
  glass: ^2.0.0+2
  http: ^1.5.0
  blurrycontainer: ^2.1.0
  intl: any
  table_calendar: ^3.2.0
  dash_chat_3: ^1.0.1
  chat_gpt_sdk: ^3.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.0
  flutter_native_splash: ^2.4.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  # --- SECCIÓN DE ASSETS CORREGIDA ---
  # Esto le dice a Flutter que incluya TODOS los archivos
  # que están dentro de la carpeta 'assets'.
  assets:
    - .env
    - assets/

  # --- Sección de Fuentes ---
  fonts:
  - family: MonosRegular
    fonts:
      - asset: fonts/FragmentMono-Regular.ttf
  - family: MonosItalic
    fonts:
      - asset: fonts/FragmentMono-Italic.ttf

# --- Configuración de Iconos de la App ---
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptove_icon_foreground: "assets/logo4.png"
  adaptive_icon_background: "#131313"